<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_Master.master" AutoEventWireup="true" CodeFile="NewsUpdate.aspx.cs" Inherits="NewsUpdate" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <link href="css/newupdate.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <div class="con-title">
              <img style="vertical-align:central; float:left;" src="image/adminnew1.png" width="30" height="30" />
              <span style="font-size:18px;margin-top:10px;float:left;">当前页面：新闻修改</span>
           </div> 
    <div class="admin_table"> 
        
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="newID" DataSourceID="SqlDataSource1" Width="1100px" Height="500px"  PageSize="4" AutoGenerateDeleteButton="True" HorizontalAlign="Left" RowStyle-HorizontalAlign="Center" RowStyle-VerticalAlign="Middle" RowStyle-Width="40px">
             <AlternatingRowStyle BackColor="#EDEDF8" HorizontalAlign="Center" />
            <Columns>
                
                <asp:BoundField DataField="newID" HeaderText="newID" InsertVisible="False" ReadOnly="True" SortExpression="newID" HeaderStyle-HorizontalAlign="Center" HeaderStyle-VerticalAlign="Middle" />
                <asp:BoundField DataField="newTitle" HeaderText="newTitle" SortExpression="newTitle" />
                <asp:BoundField DataField="newDescription" HeaderText="newDescription" SortExpression="newDescription" />
                 <asp:ImageField DataImageUrlField="newPic" HeaderText="newPic" ControlStyle-Height="50px" ControlStyle-Width="50px" >
<ControlStyle Height="50px" Width="50px"></ControlStyle>
                  </asp:ImageField>
                <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                <asp:CheckBoxField DataField="Enable" HeaderText="Enable" SortExpression="Enable" ItemStyle-CssClass="enable" />
                <asp:CommandField  ShowEditButton="True" />
                 </Columns>
            <EditRowStyle BackColor="#3366FF" ForeColor="White" HorizontalAlign="Left" />
              <FooterStyle BackColor="#6699FF" HorizontalAlign="Center" />
              <HeaderStyle BackColor="#9C9CF5" ForeColor="Black" Height="60px" />
            <PagerStyle HorizontalAlign="Center" VerticalAlign="Middle" />
             <RowStyle BackColor="White" HorizontalAlign="Center" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:AIFORUMConnectionString %>" DeleteCommand="DELETE FROM [News] WHERE [newID] = @newID" InsertCommand="INSERT INTO [News] ([newTitle], [newDescription], [newPic], [Date], [Enable]) VALUES (@newTitle, @newDescription, @newPic, @Date, @Enable)" SelectCommand="SELECT * FROM [News] ORDER BY [Date] DESC" UpdateCommand="UPDATE [News] SET [newTitle] = @newTitle, [newDescription] = @newDescription, [newPic] = @newPic, [Date] = @Date, [Enable] = @Enable WHERE [newID] = @newID">
            <DeleteParameters>
                <asp:Parameter Name="newID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="newTitle" Type="String" />
                <asp:Parameter Name="newDescription" Type="String" />
                <asp:Parameter Name="newPic" Type="String" />
                <asp:Parameter Name="Date" Type="String" />
                <asp:Parameter Name="Enable" Type="Boolean" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="newTitle" Type="String" />
                <asp:Parameter Name="newDescription" Type="String" />
                <asp:Parameter Name="newPic" Type="String" />
                <asp:Parameter Name="Date" Type="String" />
                <asp:Parameter Name="Enable" Type="Boolean" />
                <asp:Parameter Name="newID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>

