<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_Master.master" AutoEventWireup="true" CodeFile="productupdate.aspx.cs" Inherits="productupdate" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <link href="css/productupdate.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <div class="con-title">
              <img style="vertical-align:central; float:left;" src="image/adminproduct02.png" width="30" height="30" />
              <span style="font-size:18px;margin-top:10px;float:left;">当前页面：产品修改</span>
     </div>
    
    <div class="admin_table"> 
         <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="productID" DataSourceID="SqlDataSource2" Width="1100px" Height="500px"  PageSize="4" AutoGenerateDeleteButton="True" HorizontalAlign="Left" RowStyle-HorizontalAlign="Center" RowStyle-VerticalAlign="Middle" RowStyle-Width="40px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" EditRowStyle-Width="1100px">
             <AlternatingRowStyle BackColor="#EDEDF8" HorizontalAlign="Center" />
            <Columns>
                <asp:BoundField DataField="productID" HeaderText="productID" InsertVisible="False" ReadOnly="True" SortExpression="productID" HeaderStyle-HorizontalAlign="Center" HeaderStyle-VerticalAlign="Middle" ControlStyle-Width="10px" />
                <asp:BoundField DataField="productName" HeaderText="productName" SortExpression="productName" />
                <asp:ImageField DataImageUrlField="productPic" HeaderText="productPic" ControlStyle-Height="50px" ControlStyle-Width="50px" >
<ControlStyle Height="50px" Width="50px"></ControlStyle></asp:ImageField>
                <asp:BoundField DataField="className" HeaderText="className" SortExpression="className" />
                <asp:BoundField DataField="cost" HeaderText="cost" SortExpression="cost" />
                <asp:BoundField DataField="proDescription" HeaderText="proDescription" SortExpression="proDescription" />
                <asp:BoundField DataField="BrandName" HeaderText="BrandName" SortExpression="BrandName" />
                <asp:CheckBoxField DataField="Enable" HeaderText="Enable" SortExpression="Enable" ItemStyle-CssClass="enable" />
                <asp:CommandField ShowEditButton="True" /> 
            </Columns>
            <EditRowStyle BackColor="#3366FF" ForeColor="White" HorizontalAlign="Left" />
              <FooterStyle BackColor="#6699FF" HorizontalAlign="Center" />
              <HeaderStyle BackColor="#9C9CF5" ForeColor="Black" Height="60px" />
            <PagerStyle HorizontalAlign="Center" VerticalAlign="Middle" />
             <RowStyle BackColor="White" HorizontalAlign="Center" />
        </asp:GridView>
         <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:AIFORUMConnectionString %>" DeleteCommand="DELETE FROM [Products] WHERE [productID] = @productID" InsertCommand="INSERT INTO [Products] ([productName], [productPic], [proclass], [cost], [proDescription], [brand], [Enable]) VALUES (@productName, @productPic, @proclass, @cost, @proDescription, @brand, @Enable)" SelectCommand="SELECT Products.productID, Products.productName, Products.productPic, Proclass.className, Products.cost, Products.proDescription, Brand.BrandName, Products.Enable FROM Products INNER JOIN Brand ON Products.brand = Brand.BrandID INNER JOIN Proclass ON Products.proclass = Proclass.classID ORDER BY Products.productID" UpdateCommand="UPDATE [Products] SET [productName] = @productName, [productPic] = @productPic, [proclass] = @proclass, [cost] = @cost, [proDescription] = @proDescription, [brand] = @brand, [Enable] = @Enable WHERE [productID] = @productID">
             <DeleteParameters>
                 <asp:Parameter Name="productID" Type="Int32" />
             </DeleteParameters>
             <InsertParameters>
                 <asp:Parameter Name="productName" Type="String" />
                 <asp:Parameter Name="productPic" Type="String" />
                 <asp:Parameter Name="proclass" Type="Int32" />
                 <asp:Parameter Name="cost" Type="String" />
                 <asp:Parameter Name="proDescription" Type="String" />
                 <asp:Parameter Name="brand" Type="Int32" />
                 <asp:Parameter Name="Enable" Type="Boolean" />
             </InsertParameters>
             <UpdateParameters>
                 <asp:Parameter Name="productName" Type="String" />
                 <asp:Parameter Name="productPic" Type="String" />
                 <asp:Parameter Name="proclass" Type="Int32" />
                 <asp:Parameter Name="cost" Type="String" />
                 <asp:Parameter Name="proDescription" Type="String" />
                 <asp:Parameter Name="brand" Type="Int32" />
                 <asp:Parameter Name="Enable" Type="Boolean" />
                 <asp:Parameter Name="productID" Type="Int32" />
             </UpdateParameters>
         </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:AIFORUMConnectionString %>" DeleteCommand="DELETE FROM [News] WHERE [newID] = @newID" InsertCommand="INSERT INTO [News] ([newTitle], [newDescription], [newPic], [Date], [Enable]) VALUES (@newTitle, @newDescription, @newPic, @Date, @Enable)" SelectCommand="SELECT * FROM [News] ORDER BY [Date] DESC" UpdateCommand="UPDATE [News] SET [newTitle] = @newTitle, [newDescription] = @newDescription, [newPic] = @newPic, [Date] = @Date, [Enable] = @Enable WHERE [newID] = @newID">
            <DeleteParameters>
                <asp:Parameter Name="newID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="newTitle" Type="String" />
                <asp:Parameter Name="newDescription" Type="String" />
                <asp:Parameter Name="newPic" Type="String" />
                <asp:Parameter Name="Date" Type="String" />
                <asp:Parameter Name="Enable" Type="Boolean" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="newTitle" Type="String" />
                <asp:Parameter Name="newDescription" Type="String" />
                <asp:Parameter Name="newPic" Type="String" />
                <asp:Parameter Name="Date" Type="String" />
                <asp:Parameter Name="Enable" Type="Boolean" />
                <asp:Parameter Name="newID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div> 
</asp:Content>

